#ifndef QGUICONTROL_GLOBAL_H
#define QGUICONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QGUICONTROL_LIBRARY)
#  define QGUICONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QGUICONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QGUICONTROL_GLOBAL_H
