#ifndef QFLIGHTCONTROL_GLOBAL_H
#define QFLIGHTCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QFLIGHTCONTROL_LIBRARY)
#  define QFLIGHTCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QFLIGHTCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QFLIGHTCONTROL_GLOBAL_H
